# ASUS ProArt PZ13 (HT5306QA): two WSA8845 speakers on the WSA macro, DMIC
# array on the VA macro, no headset jack / no WCD codec.
Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/x1e80100/ProArt-PZ13-HiFi.conf"
	Comment "HiFi quality Music."
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
Include.wsa-init.File "/codecs/wsa884x/two-speakers/init.conf"
Include.wsam-init.File "/codecs/qcom-lpass/wsa-macro/init.conf"
