title      Debian on PZ13 (kernel 7.2.5-pz13)
linux      /pz13/vmlinuz-7.2.5-pz13
initrd     /pz13/initrd.img-7.2.5-pz13
devicetree /pz13/x1p42100-asus-proart-pz13.dtb
options    root=LABEL=pz13root rw consoleblank=0 clk_ignore_unused pd_ignore_unused arm64.nopauth
